import { CategoryCardDataType } from "../../../types";

export const CategoryDummyData: CategoryCardDataType[] = [
  {
    id: 1,
    image: require("@/assets/images/home/menu/burger.png"),
    offer: "20% OFF",
    rating: "4.5",
    deliveryTime: "30 mins",
    item: "Burger",
    shop: "Burger Hub",
    location: "Model Town, Jalandhar",
    distance: "2.3 km",
  },
  {
    id: 2,
    image: require("@/assets/images/home/menu/pizza.png"),
    offer: "15% OFF",
    rating: "4.2",
    deliveryTime: "25 mins",
    item: "Pizza",
    shop: "Pizza Point",
    location: "Urban Estate, Jalandhar",
    distance: "3.1 km",
  },
  {
    id: 3,
    image: require("@/assets/images/home/menu/salad.png"),
    offer: "10% OFF",
    rating: "4.8",
    deliveryTime: "40 mins",
    item: "Sushi",
    shop: "Sushi Express",
    location: "Lajpat Nagar, Jalandhar",
    distance: "4.7 km",
  },
  {
    id: 4,
    image: require("@/assets/images/home/menu/dosa.png"),
    offer: "25% OFF",
    rating: "4.6",
    deliveryTime: "20 mins",
    item: "Dosa",
    shop: "Dosa Plaza",
    location: "GTB Nagar, Jalandhar",
    distance: "2.9 km",
  },
  {
    id: 5,
    image: require("@/assets/images/home/menu/ice-cream.webp"),
    offer: "30% OFF",
    rating: "4.7",
    deliveryTime: "15 mins",
    item: "Ice Cream",
    shop: "Cream Bell",
    location: "Shastri Market, Jalandhar",
    distance: "1.8 km",
  },
  {
    id: 6,
    image: require("@/assets/images/home/menu/biryani.png"),
    offer: "18% OFF",
    rating: "4.4",
    deliveryTime: "35 mins",
    item: "Biryani",
    shop: "Biryani Blues",
    location: "BMC Chowk, Jalandhar",
    distance: "3.6 km",
  },
  {
    id: 7,
    image: require("@/assets/images/home/menu/pasta.png"),
    offer: "12% OFF",
    rating: "4.3",
    deliveryTime: "28 mins",
    item: "Pasta",
    shop: "Pasta Street",
    location: "Sodal Road, Jalandhar",
    distance: "4.2 km",
  },
  {
    id: 8,
    image: require("@/assets/images/home/menu/salad.png"),
    offer: "22% OFF",
    rating: "4.1",
    deliveryTime: "18 mins",
    item: "Salad",
    shop: "Green Bowl",
    location: "Rama Mandi, Jalandhar",
    distance: "5.5 km",
  },
  {
    id: 9,
    image: require("@/assets/images/home/menu/noodles.png"),
    offer: "17% OFF",
    rating: "4.0",
    deliveryTime: "32 mins",
    item: "Noodles",
    shop: "Wok Express",
    location: "Nakodar Road, Jalandhar",
    distance: "3.8 km",
  },
  {
    id: 10,
    image: require("@/assets/images/home/menu/pure-veg.png"),
    offer: "14% OFF",
    rating: "4.2",
    deliveryTime: "22 mins",
    item: "Sandwich",
    shop: "Subway",
    location: "Phagwara Gate, Jalandhar",
    distance: "2.6 km",
  },
];
