import { CategoryCardDataType } from "../../../types";

export const CategoryDummyData: CategoryCardDataType[] = [
  {
    id: 1,
    image: "@assets/images/burger.jpg",
    offer: "20% OFF",
    rating: "4.5",
    deliveryTime: "30 mins",
    item: "Burger",
    shop: "Burger Hub",
    location: "Model Town, Jalandhar",
  },
  {
    id: 2,
    image: "@assets/images/pizza.jpg",
    offer: "15% OFF",
    rating: "4.2",
    deliveryTime: "25 mins",
    item: "Pizza",
    shop: "Pizza Point",
    location: "Urban Estate, Jalandhar",
  },
  {
    id: 3,
    image: "@assets/images/sushi.jpg",
    offer: "10% OFF",
    rating: "4.8",
    deliveryTime: "40 mins",
    item: "Sushi",
    shop: "Sushi Express",
    location: "Lajpat Nagar, Jalandhar",
  },
  {
    id: 4,
    image: "@assets/images/dosa.jpg",
    offer: "25% OFF",
    rating: "4.6",
    deliveryTime: "20 mins",
    item: "Dosa",
    shop: "Dosa Plaza",
    location: "GTB Nagar, Jalandhar",
  },
  {
    id: 5,
    image: "@assets/images/icecream.jpg",
    offer: "30% OFF",
    rating: "4.7",
    deliveryTime: "15 mins",
    item: "Ice Cream",
    shop: "Cream Bell",
    location: "Shastri Market, Jalandhar",
  },
  {
    id: 6,
    image: "@assets/images/biryani.jpg",
    offer: "18% OFF",
    rating: "4.4",
    deliveryTime: "35 mins",
    item: "Biryani",
    shop: "Biryani Blues",
    location: "BMC Chowk, Jalandhar",
  },
  {
    id: 7,
    image: "@assets/images/pasta.jpg",
    offer: "12% OFF",
    rating: "4.3",
    deliveryTime: "28 mins",
    item: "Pasta",
    shop: "Pasta Street",
    location: "Sodal Road, Jalandhar",
  },
  {
    id: 8,
    image: "@assets/images/salad.jpg",
    offer: "22% OFF",
    rating: "4.1",
    deliveryTime: "18 mins",
    item: "Salad",
    shop: "Green Bowl",
    location: "Rama Mandi, Jalandhar",
  },
  {
    id: 9,
    image: "@assets/images/noodles.jpg",
    offer: "17% OFF",
    rating: "4.0",
    deliveryTime: "32 mins",
    item: "Noodles",
    shop: "Wok Express",
    location: "Nakodar Road, Jalandhar",
  },
  {
    id: 10,
    image: "@assets/images/sandwich.jpg",
    offer: "14% OFF",
    rating: "4.2",
    deliveryTime: "22 mins",
    item: "Sandwich",
    shop: "Subway",
    location: "Phagwara Gate, Jalandhar",
  },
];
