export const restaurantData: RestaurantCardType[] = [
  {
    id: 1,
    image: "https://images.unsplash.com/photo-1517248135467-4c7edcad34c4",
    name: "Spice Garden",
    rating: "4.5",
    location: "Downtown",
    popularDish: "Butter Chicken",
    offers: ["50% off up to ₹100", "Free Delivery"],
  },
  {
    id: 2,
    image: "https://images.unsplash.com/photo-1555396273-367ea4eb4db5",
    name: "Pizza Paradise",
    rating: "4.3",
    location: "Westside Mall",
    popularDish: "Margherita Pizza",
    offers: ["Buy 1 Get 1 Free", "20% off on orders above ₹500"],
  },
  {
    id: 3,
    image: "https://images.unsplash.com/photo-1552566626-52f8b828add9",
    name: "Sushi Master",
    rating: "4.7",
    location: "Marina Bay",
    popularDish: "California Roll",
    offers: ["Free Miso Soup", "15% off on first order"],
  },
  {
    id: 4,
    image: "https://images.unsplash.com/photo-1550966871-3ed3cdb5ed0c",
    name: "Burger Junction",
    rating: "4.2",
    location: "Central Park",
    popularDish: "Classic Cheeseburger",
    offers: ["Combo Meal at ₹299", "Free Fries with any burger"],
  },
  {
    id: 5,
    image: "https://images.unsplash.com/photo-1514933651103-005eec06c04b",
    name: "Tandoori Nights",
    rating: "4.6",
    location: "Old City",
    popularDish: "Tandoori Platter",
    offers: ["30% off on main course", "Free Naan"],
  },
  {
    id: 6,
    image: "https://images.unsplash.com/photo-1559339352-11d035aa65de",
    name: "Pasta Palace",
    rating: "4.4",
    location: "Riverside",
    popularDish: "Alfredo Pasta",
    offers: ["Free Garlic Bread", "20% off on pasta"],
  },
  {
    id: 7,
    image: "https://images.unsplash.com/photo-1555396273-367ea4eb4db5",
    name: "Dessert Delight",
    rating: "4.8",
    location: "Sweet Street",
    popularDish: "Chocolate Lava Cake",
    offers: ["Buy 2 Get 1 Free", "Free Ice Cream"],
  },
  {
    id: 8,
    image: "https://images.unsplash.com/photo-1550966871-3ed3cdb5ed0c",
    name: "Noodle House",
    rating: "4.3",
    location: "Chinatown",
    popularDish: "Pad Thai",
    offers: ["40% off on combos", "Free Spring Roll"],
  },
  {
    id: 9,
    image: "https://images.unsplash.com/photo-1514933651103-005eec06c04b",
    name: "Grill Masters",
    rating: "4.5",
    location: "BBQ Lane",
    popularDish: "Mixed Grill Platter",
    offers: ["25% off on platters", "Free Soft Drink"],
  },
  {
    id: 10,
    image: "https://images.unsplash.com/photo-1555396273-367ea4eb4db5",
    name: "Veggie Delight",
    rating: "4.4",
    location: "Green Valley",
    popularDish: "Paneer Butter Masala",
    offers: ["50% off on thalis", "Free Raita"],
  },
  {
    id: 11,
    image: "https://images.unsplash.com/photo-1550966871-3ed3cdb5ed0c",
    name: "Seafood Haven",
    rating: "4.7",
    location: "Harbor View",
    popularDish: "Grilled Salmon",
    offers: ["30% off on seafood", "Free Garlic Bread"],
  },
  {
    id: 12,
    image: "https://images.unsplash.com/photo-1514933651103-005eec06c04b",
    name: "Mexican Fiesta",
    rating: "4.3",
    location: "Taco Street",
    popularDish: "Chicken Burrito",
    offers: ["Free Nachos", "20% off on combos"],
  },
  {
    id: 13,
    image: "https://images.unsplash.com/photo-1555396273-367ea4eb4db5",
    name: "Thai Corner",
    rating: "4.6",
    location: "Asian Square",
    popularDish: "Green Curry",
    offers: ["Free Thai Soup", "15% off on main course"],
  },
  {
    id: 14,
    image: "https://images.unsplash.com/photo-1550966871-3ed3cdb5ed0c",
    name: "Breakfast Club",
    rating: "4.4",
    location: "Morning Lane",
    popularDish: "English Breakfast",
    offers: ["Free Coffee", "20% off before 10 AM"],
  },
  {
    id: 15,
    image: "https://images.unsplash.com/photo-1514933651103-005eec06c04b",
    name: "Kebab Kingdom",
    rating: "4.5",
    location: "Spice Road",
    popularDish: "Seekh Kebab",
    offers: ["Buy 1 Get 1 Free", "Free Chutney"],
  },
  {
    id: 16,
    image: "https://images.unsplash.com/photo-1555396273-367ea4eb4db5",
    name: "Pizza Express",
    rating: "4.2",
    location: "Italian Square",
    popularDish: "Pepperoni Pizza",
    offers: ["40% off on large pizzas", "Free Garlic Bread"],
  },
  {
    id: 17,
    image: "https://images.unsplash.com/photo-1550966871-3ed3cdb5ed0c",
    name: "Sushi Express",
    rating: "4.7",
    location: "Ocean Drive",
    popularDish: "Dragon Roll",
    offers: ["Free Miso Soup", "25% off on combos"],
  },
  {
    id: 18,
    image: "https://images.unsplash.com/photo-1514933651103-005eec06c04b",
    name: "Burger House",
    rating: "4.3",
    location: "Fast Food Lane",
    popularDish: "Double Patty Burger",
    offers: ["Combo at ₹199", "Free Fries"],
  },
  {
    id: 19,
    image: "https://images.unsplash.com/photo-1555396273-367ea4eb4db5",
    name: "Dessert Corner",
    rating: "4.6",
    location: "Sweet Street",
    popularDish: "Red Velvet Cake",
    offers: ["Buy 2 Get 1 Free", "Free Ice Cream"],
  },
  {
    id: 20,
    image: "https://images.unsplash.com/photo-1550966871-3ed3cdb5ed0c",
    name: "Noodle Express",
    rating: "4.4",
    location: "Asian Square",
    popularDish: "Hakka Noodles",
    offers: ["30% off on combos", "Free Spring Roll"],
  },
];
